/**
 * Each new term in the fibonacci sequence is generated by adding two previous terms. By starting with 1 and 2.
 * Sum up all the even-value term that the last term do not exceed four million.
 * e.g. 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144...
 * @param {number} n 
 */

//  Beside 2th term, every (3n+2)th term would also be even.
function FibNum(){
    this.prev = 1;
    this.index = 2;
    this.val = 2;
}
FibNum.prototype.next = function(){
    let temp = this.val;
    this.val += this.prev;
    this.prev = temp;
    this.index++;
    return this.val;
}


function go(limit){
    let ans = 2,
        num = new FibNum;

    while(num.next() <= limit){
        if((num.index - 2) % 3 === 0) ans += num.val;
    }
    
    return ans;
}
go(4 * (10 ** 6));